sudo: required
services:
  - docker

before_install:
  - docker build -t kratafila/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kratafila/react-test npm test -- --coverage

after_success:
  - docker build -t kratafila/multi-client -f ./client/Dockerfile ./client
  - docker build -t kratafila/multi-server -f ./server/Dockerfile ./server
  - docker build -t kratafila/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t kratafila/multi-worker -f ./worker/Dockerfile ./worker

  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take all of our images and push them to the docker hub
  - docker push kratafila/multi-client
  - docker push kratafila/multi-server
  - docker push kratafila/multi-nginx
  - docker push kratafila/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker-2
  env: MultiDocker2-env
  bucket_name: elasticbeanstalk-eu-central-1-978406833950
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
